# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b805c2693fddd65c132d35c4fdc27fa14e0ccad81866fc237a912e828690f8a37d2ebd75760657b73dd63046116d5e55c2a0aef1d1b277a33407c6fdb3ed13da

test:
  secret_key_base: b92eac8696d4f59b235875aa2e020926eb4db60e461a1a356ef42727c254951eda3e13a59f43b5609af75d47d0cba6fe16d61dc43b2589223198d23ad11ea4af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
